name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'It is your first time logging an issue here. Welcome and enjoy :)'
        pr-message: 'It is your first time logging a pull request here. Welcome and enjoy :)'
